
base:
  version_api: 1
  name_service: "Template Task"
  origins: # All hosts that can access our api
    - "http://127.0.0.1:8080"

cache:
  redis_host: "redis_template_task"
  redis_port: 6379
  default_expire_save_data: 3600  # Default save cache on 1 hour
  other_expire:
    find_templates_task: 720
    get_template_task_by_id: 300

request:
  get_current_user: "http://auth_service:8000/api/v1/auth/users/me"
