version: '3.7'

services:
  mariadb_template_task:
    container_name: mariadb_template_task
    image: mariadb:10.8
    volumes:
      - mariadb_data_template_task:/var/lib/mysql
      - ../.db_data:/var/lib/mysql
    ports:
      - "3310:3310"
    env_file:
      - ../.env
    restart: always

  task_service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    container_name: template_task_service
    volumes:
      - ../:/app/
    ports:
      - "8004:8000"
    env_file:
      - ../.env
    depends_on:
      - mariadb_template_task
    restart: always

  redis_template_task:
    image: redis
    container_name: redis_template_task
    restart: unless-stopped
    volumes:
      - redis_data_template_task:/data
      - ../.redis_data:/data
      - ../config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - "6380:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    env_file:
      - ../.env

volumes:
  mariadb_data_template_task:
  redis_data_template_task:
