
base:
  version_api: 1
  name_service: "Task"
  origins: # All hosts that can access our api
    - "http://127.0.0.1:8080"

request:
  get_current_user: "http://view_auth_service:8000/api/v1/auth/users/me"
