"""add index

Revision ID: 21a4772a9b9d
Revises: 9a88c2b81d82
Create Date: 2024-03-15 16:11:38.839361

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '21a4772a9b9d'
down_revision: Union[str, None] = '9a88c2b81d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_id', 'complete_task', ['id'], unique=False)
    op.create_foreign_key(None, 'complete_task', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_id', 'notification_task', ['id'], unique=False)
    op.create_index('idx_send_notification_at', 'notification_task', ['send_notification_at'], unique=False)
    op.create_foreign_key(None, 'notification_task', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_id_and_create_by', 'task', ['id', 'create_by'], unique=False)
    op.create_index('idx_search_name_description', 'task', ['name', 'description'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_search_name_description', table_name='task', postgresql_using='gin')
    op.drop_index('idx_id_and_create_by', table_name='task')
    op.drop_constraint(None, 'notification_task', type_='foreignkey')
    op.drop_index('idx_send_notification_at', table_name='notification_task')
    op.drop_index('idx_id', table_name='notification_task')
    op.drop_constraint(None, 'complete_task', type_='foreignkey')
    op.drop_index('idx_id', table_name='complete_task')
    # ### end Alembic commands ###
