"""empty message

Revision ID: 3227658ec714
Revises: 
Create Date: 2024-03-05 15:55:24.678185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3227658ec714'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.String(length=255), nullable=False),
                    sa.Column('create_by', sa.Integer(), nullable=False),
                    sa.Column('id_template', sa.Integer(), nullable=True),
                    sa.Column('is_complete', sa.Boolean(), nullable=True),
                    sa.Column('complete_at', sa.DateTime(), nullable=True),
                    sa.Column('planned_complete_at', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('send_notification_at', sa.DateTime(), nullable=True),
                    sa.Column('duration_repeat_send_notification_at', sa.Time(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
