version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ../nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
