version: '3.7'

services:
  task_service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    container_name: task_service
    volumes:
      - ../:/app/
    ports:
      - "8003:8000"
    env_file:
      - ../.env
    depends_on:
      - postgres_task
    restart: always

  postgres_task:
    image: postgres:12.1-alpine
    container_name: postgres_task
    restart: always
    volumes:
    - postgres_data_task:/var/lib/postgresql/data/
    - ../.db_data:/var/lib/postgresql/
    env_file:
      - ../.env

  redis_task:
    image: redis
    container_name: redis_task
    restart: unless-stopped
    volumes:
      - redis_data_task:/data
      - ../.redis_data:/data
      - ../config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379
    command: redis-server /usr/local/etc/redis/redis.conf
    env_file:
      - ../.env

volumes:
  postgres_data_task:
  redis_data_task:
