version: '3.7'

services:
  task_service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    container_name: task_service
    volumes:
      - ../:/app/
    ports:
      - "8003:8000"
    env_file:
      - ../.env
    restart: always

  postgres_task:
    image: postgres:12.1-alpine
    container_name: postgres_task
    restart: always
    volumes:
    - postgres_data_task:/var/lib/postgresql/data/
    - ../.db_data:/var/lib/postgresql/
    env_file:
      - ../.env

volumes:
  postgres_data_task:
