version: '3.7'

services:
  postgres_task:
    container_name: "postgres_task"
    image: postgres:12.1-alpine
    env_file:
      - ../.env
    restart: always
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data/

  task_service:
    container_name: "task_service"
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    ports:
      - "8003:8003"
    depends_on:
      - postgres_task

volumes:
  postgres_db_volume:

